# Generated by Django 5.0 on 2024-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='language',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='languages',
            field=models.ManyToManyField(to='myapp.language'),
        ),
    ]
