# Generated by Django 5.0 on 2024-05-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_language_remove_studentregistration_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_Amount', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.FloatField(max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentregistration')),
            ],
        ),
    ]
